import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';
import type { AppColors } from '@/constants/color-palettes';

export function createWorkoutDetailStyles(colors: AppColors) {
  return StyleSheet.create({
    scrollView: {
      flex: 1,
      paddingHorizontal: theme.spacing.md,
      paddingBottom: theme.spacing.md,
      paddingTop: 0,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: theme.spacing.md,
    },
    title: {
      fontSize: 24,
      fontWeight: '700',
      color: colors.text,
      flex: 1,
    },
    difficultyBadge: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: theme.borderRadius.md,
    },
    difficultyText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
    },
    description: {
      fontSize: 16,
      color: colors.textSecondary,
      marginBottom: theme.spacing.lg,
      lineHeight: 24,
    },
    stats: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      backgroundColor: colors.card,
      borderRadius: theme.borderRadius.lg,
      padding: theme.spacing.md,
      marginBottom: theme.spacing.lg,
    },
    stat: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    statText: {
      fontSize: 14,
      color: colors.text,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.text,
      marginBottom: theme.spacing.md,
    },
    startButton: {
      marginVertical: theme.spacing.lg,
    },
    completedButton: {
      backgroundColor: colors.success,
    },
    repeatButton: {
      marginTop: theme.spacing.sm,
    },
    activeWorkoutContainer: {
      flex: 1,
      paddingHorizontal: theme.spacing.md,
      paddingBottom: theme.spacing.md,
      paddingTop: 0,
    },
    activeWorkoutTopRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: theme.spacing.sm,
      marginBottom: theme.spacing.md,
    },
    progressIndicator: {
      flex: 1,
      minWidth: 0,
    },
    endWorkoutTopBtn: {
      paddingTop: 2,
      flexShrink: 0,
    },
    endWorkoutTopText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.error,
    },
    progressText: {
      fontSize: 16,
      color: colors.text,
      marginBottom: theme.spacing.xs,
    },
    progressBar: {
      height: 8,
      backgroundColor: colors.backgroundLight,
      borderRadius: 4,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      backgroundColor: colors.primary,
    },
    groupCardContainer: {
      backgroundColor: colors.card,
      borderRadius: theme.borderRadius.lg,
      overflow: 'hidden',
      marginBottom: theme.spacing.md,
      ...theme.shadows.small,
    },
    groupCardScroll: {
      padding: theme.spacing.md,
    },
    groupHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: theme.spacing.md,
    },
    groupLabelBadge: {
      backgroundColor: colors.primary,
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: theme.borderRadius.md,
    },
    groupLabelText: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
    },
    groupDoneBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.success,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: theme.borderRadius.sm,
      gap: 4,
    },
    groupDoneText: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.text,
    },
    groupExerciseRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.backgroundLight,
      borderRadius: theme.borderRadius.md,
      padding: theme.spacing.sm,
      marginBottom: theme.spacing.sm,
    },
    groupExerciseRowDone: {
      opacity: 0.55,
    },
    groupExerciseInfo: {
      flex: 1,
      marginRight: theme.spacing.sm,
    },
    groupExerciseName: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 2,
    },
    groupExerciseNameDone: {
      textDecorationLine: 'line-through',
    },
    groupExerciseMeta: {
      fontSize: 13,
      color: colors.textSecondary,
    },
    groupExerciseNotes: {
      fontSize: 12,
      color: colors.textSecondary,
      fontStyle: 'italic',
      marginTop: 2,
    },
    completeExBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 2,
      borderColor: colors.success,
      justifyContent: 'center',
      alignItems: 'center',
    },
    completeExBtnDone: {
      backgroundColor: colors.success,
      borderColor: colors.success,
    },
    exerciseBlock: {
      marginBottom: theme.spacing.sm,
    },
    videoThumbWrap: {
      alignSelf: 'center',
      width: '100%',
      aspectRatio: 16 / 9,
      borderRadius: theme.borderRadius.md,
      overflow: 'hidden',
      marginBottom: 6,
      backgroundColor: colors.backgroundLight,
    },
    videoThumbImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    videoPlayBadge: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      marginTop: -22,
      marginLeft: -22,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(0,0,0,0.55)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    videoCloseBtn: {
      position: 'absolute',
      top: 6,
      right: 6,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: 'rgba(0,0,0,0.7)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 10,
    },
    videoCloseBtnText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '700',
    },
    detailGroupHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: theme.spacing.sm,
      marginTop: theme.spacing.md,
    },
    detailGroupLabel: {
      fontSize: 17,
      fontWeight: '700',
      color: colors.primary,
    },
    detailGroupCount: {
      fontSize: 13,
      color: colors.textSecondary,
    },
    notesContainer: {
      padding: theme.spacing.md,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    notesLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textSecondary,
      marginBottom: theme.spacing.xs,
    },
    notes: {
      fontSize: 16,
      color: colors.text,
      lineHeight: 24,
    },
    timerContainer: {
      padding: theme.spacing.md,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    timerLabel: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.text,
      marginBottom: theme.spacing.sm,
    },
    swipeInstructions: {
      padding: theme.spacing.md,
      alignItems: 'center',
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    swipeText: {
      fontSize: 14,
      color: colors.textSecondary,
      fontStyle: 'italic',
    },
    noteButton: {
      marginBottom: theme.spacing.md,
    },
    completeButton: {
      marginBottom: theme.spacing.md,
      backgroundColor: colors.success,
    },
    modalOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.overlay,
      justifyContent: 'center',
      alignItems: 'center',
      padding: theme.spacing.md,
      zIndex: 1000,
    },
    modalContent: {
      backgroundColor: colors.card,
      borderRadius: theme.borderRadius.lg,
      padding: theme.spacing.lg,
      width: '100%',
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.text,
      marginBottom: theme.spacing.md,
    },
    noteInput: {
      marginBottom: theme.spacing.md,
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: theme.spacing.md,
    },
    modalButton: {
      minWidth: 100,
    },
    videoModalOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.background,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1000,
    },
    videoModalContent: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
    },
    closeVideoButton: {
      position: 'absolute',
      top: 40,
      right: 20,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.card,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1001,
    },
    closeVideoText: {
      fontSize: 24,
      fontWeight: '700',
      color: colors.text,
    },
    video: {
      width: '100%',
      height: 300,
    },
    completionView: {
      flex: 1,
      backgroundColor: colors.background,
      justifyContent: 'center',
      alignItems: 'center',
      padding: theme.spacing.xl,
    },
    completionOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.overlay,
      justifyContent: 'center',
      alignItems: 'center',
      padding: theme.spacing.md,
      zIndex: 1000,
    },
    completionContent: {
      backgroundColor: colors.card,
      borderRadius: theme.borderRadius.lg,
      padding: theme.spacing.xxl,
      width: '100%',
      maxWidth: 400,
      alignItems: 'center',
      ...theme.shadows.medium,
    },
    completionIcon: {
      marginBottom: theme.spacing.md,
    },
    completionTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: colors.text,
      marginBottom: theme.spacing.md,
      textAlign: 'center',
    },
    completionText: {
      fontSize: 16,
      color: colors.textSecondary,
      marginBottom: theme.spacing.lg,
      textAlign: 'center',
      lineHeight: 24,
    },
    completionButton: {
      minWidth: 200,
    },
  });
}
